name: stacked_app
description: Checking out stacked concept flow


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  stacked_services: ^0.5.4+3
  built_value: ^7.1.0
  stacked: ^1.7.6
  built_collection: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
